---
- name: install redis
  homebrew:
    name: redis
    state: present

- name: configure redis to launch on startup
  shell: ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents/ && launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
