---
- name: install leiningen
  homebrew:
    name: leiningen
    state: present

- name: install boot
  homebrew:
    name: boot-clj
    state: present

- name: install inlein
  get_url:
    url: https://github.com/hyPiRion/inlein/releases/download/0.2.0/inlein
    dest: ~/bin/inlein
    mode: 0755
