---
- name: install nvm
  homebrew:
    name: nvm
    state: present

# - name: install latest node version
#   shell: source $(brew --prefix nvm)/nvm.sh && nvm install node

- name: install yarn
  homebrew:
    name: yarn
    state: present

- name: install npm
  homebrew:
    name: npm
    state: present
