---
- name: check if public key exists
  stat:
    path: ~/.ssh/id_rsa
  register: id_rsa_result

- name: generate new public key
  shell: ssh-keygen -t rsa -b 4096 -C "{{email}}" -f $HOME/.ssh/id_rsa
  when: id_rsa_result.stat.exists != true

- name: install xcode
  shell: xcode-select --install
  ignore_errors: yes

- name: check for homebrew
  shell: which brew
  register: brew_installed
  ignore_errors: yes

- name: install homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when: brew_installed.stdout == ''

- name: disable brew analytics
  shell: brew analytics off

- name: install ag (the silver searcher)
  homebrew:
    name: the_silver_searcher
    state: present

- name: install tmux
  homebrew:
    name: tmux
    state: present

- name: install iterm2
  homebrew_cask:
    name: iterm2
    state: present
  ignore_errors: yes

- name: install gnu-tar
  homebrew:
    name: gnu-tar
    state: present

- name: install chrome-devtools
  homebrew_cask:
    name: chrome-devtools
    state: present

- name: install intellij-idea
  homebrew_cask:
    name: intellij-idea
    state: present

- name: install github
  homebrew_cask:
    name: github
    state: present

- name: install visual-studio-code
  homebrew_cask:
    name: visual-studio-code
    state: present
  ignore_errors: yes

- name: install beyond-compare
  homebrew_cask:
    name: beyond-compare
    state: present

- name: install filezilla
  homebrew_cask:
    name: filezilla
    state: present

- name: install zoomus
  homebrew_cask:
    name: zoomus
    state: present

- name: install maven
  homebrew_cask:
    name: maven
    state: present
  ignore_errors: yes

- name: install slack
  homebrew_cask:
    name: slack
    state: present

- name: install spectacle
  homebrew_cask:
    name: spectacle
    state: present