---
- name: install postgres
  homebrew:
    name: postgres
    state: present

- name: configure postgres to launch on startup
  shell: ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents/ && launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist
