---
- name: install postgres
  homebrew:
    name: postgres
    state: present

- name: configure postgres to launch on startup
  shell: brew services start postgresql

- name: check to see if there is a database
  shell: psql
  register: psql_result
  ignore_errors: yes

- name: create user db if it does not exist
  shell: createdb
  when: "'FATAL' in psql_result.stderr"
